version: "3.8"
services:
  db:
    image: postgres
    restart: always
    networks:
      - "backend-network"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
  algo_trading:
    build: .
    networks:
      - "backend-network"
    volumes:
      - ./src:/src
volumes:
  db-data:
    driver: local
networks:
  backend-network:
    driver: bridge
